model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKLWithJePA
  params:
    monitor: "val/rec_loss"
    embed_dim: 16
    encoder_ckpt: 'jepa_weights/vit_huge_14.pth'
    image_size: 224
    patch_size: 14
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 15001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: True
    train:
      target: ldm.data.mscoco.MSCOCODataset
      params:
        size: 224
        out_size: 256
        data_dir: '/usr1/data/dataset/mscoco2017'
        split: 'train'
    validation:
      target: ldm.data.mscoco.MSCOCODataset
      params:
        size: 224
        out_size: 256
        data_dir: '/usr1/data/dataset/mscoco2017'
        split: 'val'

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
